[package]
name = "generator"
version = "0.1.0"
authors = ["mohsinali-iot <mohsinali481997@gmail.com>"]
edition = "2018"
description="description of your program"
license="MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
